/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yg0R2' at '6/2/16 11:43 AM' with Gradle 2.13
 *
 * @author Yg0R2, @date 6/2/16 11:43 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
